spring:
  mongodb:
    uri: mongodb://${PAYMENT_DB_USERNAME}:${PAYMENT_DB_PASSWORD}@localhost:${MONGO_PORT}/${PAYMENT_DB_NAME}?authSource=${PAYMENT_DB_NAME}
    representation:
      uuid: standard
  kafka:
    bootstrap-servers: localhost:${KAFKA_PORT}
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: https://localhost:${KC_HTTPS_PORT}/realms/${APP_REALM}/protocol/openid-connect/certs
          issuer-uri: https://localhost:${KC_HTTPS_PORT}/realms/${APP_REALM}
          audience: ${APP_CLIENT_ID}
  grpc:
    client:
      channels:
        order-service-grpc:
          address: 'localhost:${ORDER_GRPC_SERVER_PORT}'
          negotiation-type: plaintext

app:
  liquibase:
    uri: ${spring.mongodb.uri}

logging:
  level:
    root: INFO
    com.minispring.paymentservice: DEBUG
    org.springframework.data.mongodb.core.MongoTemplate: DEBUG