spring:
  mongodb:
    uri: ${PAYMENT_DB_LOCAL_URL}
    representation:
      uuid: standard
  kafka:
    bootstrap-servers: 'localhost:9092'
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${APP_JWK_SET_URI_LOCAL}
          issuer-uri: ${APP_ISSUER_URI_LOCAL}
          audience: ${APP_CLIENT_ID}
logging:
  level:
    root: INFO
    org.springframework.data.mongodb.core.MongoTemplate: INFO
app:
  liquibase:
    uri: ${PAYMENT_DB_LOCAL_URL}